### ISSUE TITLE
Fix chat form

### ISSUE THREAD

**Issue by L4nx** [qwqdanchun/DcRat#21]
Victim cannot send message because "send" button isnt showing

**Comment by qwqdanchun** [comment]
can you give me a capture



---Original---
From: ***@***.***&gt;
Date: Sat, May 15, 2021 20:45 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [qwqdanchun/DcRat] Fix chat form (#21)




 
Victim cannot send message because "send" button isnt showing

**Comment by killzone559pl** [comment]
> Victim cannot send message because "send" button isnt showing

Its false information. Its working in newest build, you need to download a release from auto build.

**Comment by L4nx** [comment]
> > Victim cannot send message because "send" button isnt showing
> 
> Its false information. Its working in newest build, you need to download a release from auto build.

uhh lemme try

**Comment by L4nx** [comment]
![image](https://user-images.githubusercontent.com/68964753/118373042-e4a9b500-b5b4-11eb-943f-628357903ea2.png)

**Comment by L4nx** [comment]
before it wasnt showing the button but the button doesnt look very good

**Comment by killzone559pl** [comment]
> before it wasnt showing the button but the button doesnt look very good

I know. I reported this issue to @qwqdanchun, and as you can see in newest build it's working. Not looking perfect but working 100%. In previous version send button was cut in half, it was visible but not fully. I tested it a lot 😄 

So yeah it's working. @qwqdanchun Said that he is not good in design, but button is visible now in 100% so that's good
