### ISSUE TITLE
rat not connecting from albania vpn

### ISSUE THREAD

**Issue by LelouchViBri** [qwqdanchun/DcRat#32]
**Describe the bug**
Rat not connecting from albania vpn

**To Reproduce**
I just use a vpn, connect to albania and then open the client, and the rat is not connecting to the server (it's open in task manager and also sends a syn) but it's not connecting.
if i change vpn to another country then it connects just fine.

tried many other different countries and they seem to connect just fine

**Comment by qwqdanchun** [comment]
this maybe caused by your vpn,try to use another to test .



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 6, 2021 21:06 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [qwqdanchun/DcRat] rat not connecting from albania vpn (#32)




 
Describe the bug
 Rat not connecting from albania vpn
 
To Reproduce
 Steps to reproduce the behavior:
 I just use a vpn, connect to albania and then open the client, and the rat is not connecting to the server (it's open in task manager and also sends a syn) but it's not connecting.
 if i change vpn to another country then it connects just fine.
 
tried many other different countries and they seem to connect just fine
