### ISSUE TITLE
远控很不错奈何我不免杀

### ISSUE THREAD

**Issue by heiyanmaster** [qwqdanchun/DcRat#38]
远控很好，可是我没有框架免杀咋办，求个框架吖~~~

**Comment by qwqdanchun** [comment]
建议自己找或者写个shellcode loader，可以很方便的免杀



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月16日(周五) 晚上10:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qwqdanchun/DcRat] 远控很不错奈何我不免杀 (#38)




 
远控很好，可是我没有框架免杀咋办，求个框架吖~~~

**Comment by heiyanmaster** [comment]
> 
> 建议自己找或者写个shellcode loader，可以很方便的免杀
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月16日(周五) 晚上10:14 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [qwqdanchun/DcRat] 远控很不错奈何我不免杀 (#38) 远控很好，可是我没有框架免杀咋办，求个框架吖~~~ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我不会啊...

**Comment by qwqdanchun** [comment]
这个就没办法了，哈哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月16日(周五) 晚上10:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qwqdanchun/DcRat] 远控很不错奈何我不免杀 (#38)




  
建议自己找或者写个shellcode loader，可以很方便的免杀
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月16日(周五) 晚上10:14 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [qwqdanchun/DcRat] 远控很不错奈何我不免杀 (#38) 远控很好，可是我没有框架免杀咋办，求个框架吖~~~ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我不会啊...

**Comment by heiyanmaster** [comment]
> 这个就没办法了，哈哈
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年7月16日(周五) 晚上10:50 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [qwqdanchun/DcRat] 远控很不错奈何我不免杀 (#38) 建议自己找或者写个shellcode loader，可以很方便的免杀 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月16日(周五) 晚上10:14 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [qwqdanchun/DcRat] 远控很不错奈何我不免杀 (#38) 远控很好，可是我没有框架免杀咋办，求个框架吖~~~ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 我不会啊... — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

兄弟qq多少帮帮我吧分享给你2t

**Comment by qwqdanchun** [comment]
聊天可以加群814084837，但是我不会帮做免杀之类的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月17日(周六) 下午4:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qwqdanchun/DcRat] 远控很不错奈何我不免杀 (#38)




  
这个就没办法了，哈哈
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月16日(周五) 晚上10:50 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [qwqdanchun/DcRat] 远控很不错奈何我不免杀 (#38) 建议自己找或者写个shellcode loader，可以很方便的免杀 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年7月16日(周五) 晚上10:14 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [qwqdanchun/DcRat] 远控很不错奈何我不免杀 (#38) 远控很好，可是我没有框架免杀咋办，求个框架吖~~~ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 我不会啊... — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
兄弟qq多少帮帮我吧分享给你2t
